<a href="https://colab.research.google.com/github/davidlealo/sic_2026_c-p_cohort_1/blob/main/proyectos/equipo-9/notebooks/01_eda.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!wget https://raw.githubusercontent.com/davidlealo/sic_2026_c-p_cohort_1/refs/heads/main/proyectos/equipo-9/data/dataset_original.csv

--2026-06-20 01:25:13--  https://raw.githubusercontent.com/davidlealo/sic_2026_c-p_cohort_1/refs/heads/main/proyectos/equipo-9/data/dataset_original.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178693 (175K) [text/plain]
Saving to: ‘dataset_original.csv’

dataset_original.cs 100%[===================>] 174.50K  --.-KB/s    in 0.02s

2026-06-20 01:25:13 (7.10 MB/s) - ‘dataset_original.csv’ saved [178693/178693]

In [ ]:
# Análisis Exploratorio de Datos (EDA)
import pandas as pd
df = pd.read_csv('dataset_original.csv')
display(df.head())

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,NaN
1,FB000002,Tops,Uniqlo,Winter,L,Pink,119.64,0.0,119.64,2025-08-06,2,2.5,False,NaN
2,FB000003,Accessories,Uniqlo,Winter,NaN,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,NaN
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,NaN
4,FB000005,Tops,Banana Republic,Winter,XL,Black,105.02,0.0,105.02,2025-08-06,10,NaN,False,NaN

In [ ]:
display(df.describe())

,original_price,markdown_percentage,current_price,stock_quantity,customer_rating
count,2176.000000,2176.000000,2176.000000,2176.000000,1814.000000
mean,97.200340,12.144715,85.499596,24.937960,2.986604
std,51.637345,18.417786,50.091354,14.451387,1.159722
min,15.140000,0.000000,7.290000,0.000000,1.000000
25%,57.872500,0.000000,46.845000,13.000000,2.000000
50%,88.600000,0.000000,74.885000,25.000000,3.000000
75%,127.630000,22.425000,112.865000,37.000000,4.000000
max,249.980000,59.900000,249.980000,50.000000,5.000000

In [ ]:
display(df.info())
# Observación: El dataset tiene buena estructura, revisaremos nulos en el siguiente paso.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2176 entries, 0 to 2175
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   product_id           2176 non-null   object
 1   category             2176 non-null   object
 2   brand                2176 non-null   object
 3   season               2176 non-null   object
 4   size                 1685 non-null   object
 5   color                2176 non-null   object
 6   original_price       2176 non-null   float64
 7   markdown_percentage  2176 non-null   float64
 8   current_price        2176 non-null   float64
 9   purchase_date        2176 non-null   object
 10  stock_quantity       2176 non-null   int64
 11  customer_rating      1814 non-null   float64
 12  is_returned          2176 non-null   bool
 13  return_reason        320 non-null    object
dtypes: bool(1), float64(4), int64(1), object(8)
memory usage: 223.3+ KB

None

In [ ]:
# Valores unicos de df.return_reason
df.return_reason.unique()

array([nan, 'Color Mismatch', 'Size Issue', 'Damaged', 'Quality Issue',
       'Changed Mind', 'Wrong Item'], dtype=object)

In [ ]:
df['return_reason'].value_counts()

return_reason
Changed Mind      68
Size Issue        60
Quality Issue     55
Wrong Item        47
Color Mismatch    46
Damaged           44
Name: count, dtype: int64

In [ ]:
68+60+55+47+46+44

320

In [ ]:
df['return_reason'].isnull().sum()

np.int64(1856)

Vamos a verificar la relación entre `is_returned` y `return_reason`:

In [ ]:
# Verificar si hay valores NaN en 'return_reason' cuando 'is_returned' es True
null_reasons_for_returned = df[df['is_returned'] == True]['return_reason'].isnull().sum()
print(f"Número de 'return_reason' nulos cuando 'is_returned' es True: {null_reasons_for_returned}")

Número de 'return_reason' nulos cuando 'is_returned' es True: 0

In [ ]:
# Verificar si hay valores no NaN en 'return_reason' cuando 'is_returned' es False
not_null_reasons_for_not_returned = df[df['is_returned'] == False]['return_reason'].notnull().sum()
print(f"Número de 'return_reason' no nulos cuando 'is_returned' es False: {not_null_reasons_for_not_returned}")

if null_reasons_for_returned == 0 and not_null_reasons_for_not_returned == 0:
    print("\nLa hipótesis es correcta: 'return_reason' tiene un valor solo si 'is_returned' es True, y es NaN si 'is_returned' es False.")
else:
    print("\nLa hipótesis no es completamente correcta. Revisa los conteos anteriores.")

Número de 'return_reason' no nulos cuando 'is_returned' es False: 0

La hipótesis es correcta: 'return_reason' tiene un valor solo si 'is_returned' es True, y es NaN si 'is_returned' es False.

In [ ]:
df['return_reason'] = df['return_reason'].fillna('no_returned')

# Opcional: Verificar los cambios mostrando el conteo de valores de nuevo
print("Conteo de valores de 'return_reason' después de reemplazar NaN:")
display(df['return_reason'].value_counts())

Conteo de valores de 'return_reason' después de reemplazar NaN:

return_reason
no_returned       1856
Changed Mind        68
Size Issue          60
Quality Issue       55
Wrong Item          47
Color Mismatch      46
Damaged             44
Name: count, dtype: int64

In [ ]:
# Opcional: Verificar que no queden NaNs en la columna
print("Número de NaNs en 'return_reason' después de la operación:")
display(df['return_reason'].isnull().sum())

Número de NaNs en 'return_reason' después de la operación:

np.int64(0)

In [ ]:
320+1856

2176

In [ ]:
df["size"].unique()

array(['XL', 'L', nan, 'S', 'XXL', 'XS', 'M'], dtype=object)

In [ ]:
size_by_category = df.groupby('category')['size'].value_counts(dropna=False)
display(size_by_category)

category     size
Accessories  NaN     402
Bottoms      XXL      72
             XS       69
             L        62
             S        58
             M        57
             XL       53
             NaN      21
Dresses      XL       71
             S        52
             XS       47
             XXL      46
             M        43
             L        41
             NaN      17
Outerwear    S        62
             XS       60
             L        55
             M        51
             XXL      50
             XL       44
             NaN      12
Shoes        XS       67
             S        61
             M        60
             XL       57
             L        55
             XXL      50
             NaN      22
Tops         S        61
             XXL      61
             L        60
             XL       58
             XS       58
             M        44
             NaN      17
Name: count, dtype: int64

In [ ]:
nan_size_products = df[df['size'].isna()]
display(nan_size_products.groupby('category').head(3))

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
2,FB000003,Accessories,Uniqlo,Winter,NaN,Black,33.80,0.0,33.80,2025-08-06,22,4.3,False,no_returned
5,FB000006,Accessories,Zara,Fall,NaN,White,35.03,35.4,22.63,2025-08-06,38,2.9,True,Color Mismatch
15,FB000016,Accessories,Mango,Winter,NaN,Green,67.57,0.0,67.57,2025-08-06,17,2.4,False,no_returned
39,FB000040,Bottoms,Banana Republic,Winter,NaN,Purple,101.72,0.0,101.72,2025-08-06,40,NaN,False,no_returned
63,FB000064,Shoes,H&M,Summer,NaN,Green,106.18,18.0,87.07,2025-08-06,11,4.5,False,no_returned
145,FB000146,Tops,Uniqlo,Winter,NaN,Beige,91.80,15.8,77.30,2025-08-06,30,4.2,False,no_returned
232,FB000233,Dresses,Forever21,Winter,NaN,Black,56.34,22.4,43.72,2025-08-06,37,2.5,True,Wrong Item
233,FB000234,Tops,Gap,Fall,NaN,Beige,88.41,0.0,88.41,2025-08-06,24,4.4,False,no_returned
239,FB000240,Shoes,Zara,Fall,NaN,Brown,74.48,0.0,74.48,2025-08-06,24,3.7,False,no_returned
270,FB000271,Dresses,Forever21,Summer,NaN,Navy,92.73,0.0,92.73,2025-08-06,15,1.4,False,no_returned
277,FB000278,Dresses,Zara,Winter,NaN,Blue,89.69,0.0,89.69,2025-08-06,50,4.3,False,no_returned
288,FB000289,Shoes,Mango,Summer,NaN,Brown,169.75,0.0,169.75,2025-08-06,5,2.7,False,no_returned
322,FB000323,Bottoms,H&M,Spring,NaN,White,106.37,0.0,106.37,2025-04-06,37,4.9,False,no_returned
334,FB000335,Bottoms,Mango,Fall,NaN,Pink,88.40,0.0,88.40,2025-08-06,1,1.4,False,no_returned
394,FB000395,Tops,Zara,Winter,NaN,Blue,111.72,33.3,74.52,2025-08-06,47,2.0,True,Quality Issue
488,FB000489,Outerwear,Banana Republic,Fall,NaN,Pink,223.69,6.3,209.60,2025-08-06,18,1.9,False,no_returned
514,FB000515,Outerwear,Ann Taylor,Summer,NaN,White,80.35,0.0,80.35,2025-08-06,28,2.9,False,no_returned
717,FB000718,Outerwear,Banana Republic,Winter,NaN,Green,225.92,43.7,127.19,2025-08-06,30,3.2,False,no_returned

In [ ]:
df['purchase_date'].unique() #YYYYmmdd

array(['2025-07-05', '2025-08-06', '2025-07-07', '2024-10-29',
       '2025-03-24', '2025-04-25', '2025-01-04', '2024-09-24',
       '2025-06-11', '2024-10-24', '2025-04-16', '2024-10-16',
       '2025-05-03', '2025-06-12', '2025-07-10', '2024-10-25',
       '2025-06-01', '2025-01-26', '2025-04-01', '2025-05-10',
       '2024-10-14', '2024-09-13', '2025-07-25', '2025-02-10',
       '2024-12-29', '2024-09-09', '2024-11-08', '2025-06-17',
       '2025-07-20', '2024-09-06', '2024-11-25', '2025-07-04',
       '2025-01-14', '2024-12-06', '2025-03-05', '2024-11-16',
       '2025-04-12', '2024-11-04', '2025-01-13', '2024-10-01',
       '2024-11-03', '2025-07-16', '2025-02-17', '2025-07-24',
       '2024-09-15', '2024-10-03', '2024-09-12', '2025-06-20',
       '2024-09-17', '2024-12-19', '2024-08-28', '2024-12-03',
       '2024-09-26', '2024-10-04', '2024-11-23', '2024-09-28',
       '2025-04-29', '2025-05-23', '2025-07-17', '2024-08-21',
       '2025-01-30', '2024-12-27', '2024-11-02', '2024-10-10',
       '2025-07-14', '2024-08-16', '2025-08-01', '2025-05-08',
       '2025-04-26', '2024-12-25', '2024-09-27', '2025-06-27',
       '2025-03-30', '2024-12-23', '2025-03-31', '2025-01-22',
       '2025-05-26', '2024-12-04', '2024-11-21', '2025-04-06',
       '2025-06-13', '2025-05-09', '2025-06-10', '2025-02-01',
       '2025-04-23', '2025-02-09', '2025-07-29', '2025-02-15',
       '2025-02-23', '2024-10-08', '2024-10-23', '2024-09-21',
       '2025-03-14', '2024-12-02', '2024-08-20', '2025-06-18',
       '2024-12-20', '2025-01-23', '2025-07-31', '2025-07-03',
       '2024-09-07', '2025-05-06', '2024-08-08', '2024-11-07',
       '2024-08-07', '2024-09-25', '2025-01-18', '2024-11-14',
       '2025-02-05', '2025-04-10', '2025-07-23', '2025-04-09',
       '2025-07-22', '2024-11-27', '2025-03-28', '2025-02-11',
       '2025-03-18', '2025-02-28', '2025-03-06', '2025-03-25',
       '2025-01-21', '2024-10-12', '2025-06-07', '2025-07-27',
       '2025-03-20', '2025-01-31', '2025-04-04', '2025-07-02',
       '2024-10-07', '2024-10-26', '2025-06-24', '2025-05-16',
       '2025-07-15', '2025-08-05', '2024-09-01', '2025-02-03',
       '2024-09-10', '2025-01-19', '2025-04-18', '2025-03-13',
       '2024-09-08', '2025-07-11', '2024-08-29', '2024-11-17',
       '2025-08-02', '2025-04-13', '2025-01-07', '2024-11-22',
       '2025-01-27', '2025-06-04', '2024-09-22', '2025-05-15',
       '2024-12-21', '2024-12-16', '2024-08-18', '2025-02-24',
       '2024-08-06', '2025-05-19', '2025-07-30', '2025-07-28',
       '2025-05-21', '2024-12-08', '2025-06-05', '2025-03-17',
       '2024-10-02', '2024-11-09', '2024-12-24', '2025-04-22',
       '2025-05-12', '2025-03-29', '2024-11-06', '2024-11-28',
       '2024-11-15', '2025-02-14', '2025-04-17', '2025-03-27',
       '2024-08-17', '2025-04-30', '2025-07-08', '2025-03-22',
       '2025-02-04', '2024-08-10', '2025-01-29', '2025-04-15',
       '2025-04-02', '2025-05-28', '2024-11-26', '2025-06-28',
       '2025-03-07', '2025-01-17', '2024-12-30', '2025-06-09',
       '2025-02-18', '2024-10-21', '2024-09-19', '2025-01-12',
       '2025-04-05', '2025-04-14', '2024-09-02', '2025-02-07',
       '2025-05-18', '2025-02-26', '2024-12-17', '2025-02-16',
       '2025-05-30', '2024-08-12', '2025-05-11', '2025-02-20',
       '2024-12-10', '2025-03-11', '2025-03-03', '2024-12-05',
       '2024-08-26', '2025-05-01', '2025-07-26', '2024-11-11',
       '2025-01-08', '2024-08-15', '2024-08-19', '2025-04-07',
       '2024-11-12', '2024-12-12', '2024-12-07', '2024-11-20',
       '2025-05-17', '2025-02-13', '2025-01-02', '2025-06-15',
       '2024-11-13', '2025-05-14', '2024-09-30', '2025-01-24',
       '2024-09-03', '2024-09-05', '2024-08-22', '2025-05-20',
       '2025-04-28', '2024-08-27', '2025-02-12', '2025-03-09',
       '2025-04-24', '2025-07-13', '2024-08-25', '2025-06-14',
       '2025-08-03', '2025-05-27', '2024-11-24', '2024-10-27',
       '2024-12-31', '2024-10-15', '2025-05-02', '2025-05-29',
       '2025-01-09', '2025-03-15', '2025-03-26', '2025-06-08',
       '2024-09-20', '2025-01-15', '2025-01-10', '2024-08-30',
       '2025-07-09', '2024-10-19', '2025-05-24', '2025-06-03',
       '2024-10-31', '2024-12-22', '2025-06-19', '2025-03-08',
       '2024-08-23', '2024-09-29', '2025-01-28', '2025-05-07',
       '2025-03-16'], dtype=object)

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])
nov_products = df[df['purchase_date'].dt.month == 11]
display(nov_products)

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
102,FB000103,Dresses,Uniqlo,Spring,S,Beige,126.37,0.0,126.37,2024-11-08,25,1.8,False,no_returned
117,FB000118,Dresses,Zara,Spring,M,Navy,133.82,0.0,133.82,2024-11-25,12,1.7,False,no_returned
130,FB000131,Dresses,Banana Republic,Spring,XL,Purple,79.13,0.0,79.13,2024-11-16,11,3.6,False,no_returned
132,FB000133,Tops,Mango,Spring,XL,White,116.61,0.0,116.61,2024-11-04,31,NaN,False,no_returned
140,FB000141,Dresses,Ann Taylor,Spring,XS,Gray,131.50,0.0,131.50,2024-11-03,5,NaN,False,no_returned
196,FB000197,Bottoms,Ann Taylor,Spring,XXL,Red,32.10,51.7,15.50,2024-11-23,27,NaN,False,no_returned
200,FB000201,Bottoms,Zara,Spring,XS,Green,42.91,33.3,28.62,2024-11-23,18,NaN,False,no_returned
227,FB000228,Bottoms,H&M,Spring,XS,Black,42.29,15.8,35.61,2024-11-02,11,1.6,False,no_returned
319,FB000320,Shoes,Uniqlo,Spring,S,Beige,152.53,0.0,152.53,2024-11-21,24,4.2,False,no_returned
483,FB000484,Shoes,Uniqlo,Spring,XS,Blue,74.54,0.0,74.54,2024-11-07,4,3.5,False,no_returned
508,FB000509,Bottoms,Mango,Spring,XL,Purple,42.47,0.0,42.47,2024-11-14,33,4.5,True,Changed Mind
537,FB000538,Outerwear,Uniqlo,Spring,L,Purple,217.89,49.4,110.25,2024-11-27,42,2.9,False,no_returned
764,FB000765,Shoes,H&M,Spring,L,Blue,63.12,0.0,63.12,2024-11-08,35,2.9,False,no_returned
800,FB000801,Tops,Mango,Spring,XL,Gray,49.62,0.8,49.22,2024-11-17,22,2.3,False,no_returned
828,FB000829,Shoes,Ann Taylor,Spring,XL,Gray,162.97,0.0,162.97,2024-11-22,47,2.2,True,Wrong Item
862,FB000863,Dresses,Mango,Spring,S,Purple,136.20,44.3,75.86,2024-11-21,49,NaN,False,no_returned
938,FB000939,Tops,Ann Taylor,Spring,XXL,Purple,69.77,0.0,69.77,2024-11-09,29,5.0,False,no_returned
959,FB000960,Tops,Zara,Spring,S,Brown,30.90,5.5,29.20,2024-11-06,25,1.4,False,no_returned
964,FB000965,Shoes,Mango,Spring,XXL,Green,92.35,23.6,70.56,2024-11-28,32,2.2,False,no_returned
980,FB000981,Accessories,Forever21,Spring,NaN,Blue,52.69,40.2,31.51,2024-11-15,7,2.7,False,no_returned
986,FB000987,Outerwear,Uniqlo,Spring,XL,White,122.92,0.0,122.92,2024-11-06,41,2.9,False,no_returned
1090,FB001091,Accessories,Gap,Spring,NaN,White,72.83,0.0,72.83,2024-11-26,6,2.0,False,no_returned
1110,FB001111,Outerwear,Banana Republic,Spring,XXL,Brown,103.65,0.0,103.65,2024-11-16,4,1.0,False,no_returned
1137,FB001138,Shoes,Uniqlo,Spring,M,Green,138.41,0.0,138.41,2024-11-17,40,3.1,False,no_returned
1365,FB001366,Outerwear,Forever21,Spring,S,Green,161.25,48.4,83.20,2024-11-11,32,NaN,False,no_returned
1369,FB001370,Shoes,Mango,Spring,S,Brown,109.15,0.0,109.15,2024-11-11,11,NaN,False,no_returned
1417,FB001418,Accessories,Zara,Spring,NaN,Brown,62.21,1.8,61.09,2024-11-03,4,2.3,False,no_returned
1454,FB001455,Accessories,Uniqlo,Spring,NaN,Purple,63.42,0.0,63.42,2024-11-12,19,2.9,True,Color Mismatch
1500,FB001501,Outerwear,H&M,Spring,L,Beige,161.51,0.0,161.51,2024-11-02,22,4.7,False,no_returned
1505,FB001506,Shoes,Uniqlo,Spring,L,Brown,199.33,44.3,111.03,2024-11-20,19,1.8,False,no_returned
1510,FB001511,Bottoms,Zara,Spring,M,Gray,25.97,0.0,25.97,2024-11-28,31,1.2,False,no_returned
1524,FB001525,Bottoms,Zara,Spring,XS,Blue,105.21,0.0,105.21,2024-11-02,41,4.9,False,no_returned
1537,FB001538,Tops,Banana Republic,Spring,XXL,Pink,70.48,0.0,70.48,2024-11-27,22,1.2,False,no_returned
1550,FB001551,Tops,Gap,Spring,NaN,White,74.13,0.0,74.13,2024-11-13,23,NaN,False,no_returned
1735,FB001736,Shoes,Ann Taylor,Spring,XS,Gray,115.77,0.0,115.77,2024-11-24,43,NaN,False,no_returned
1810,FB001811,Accessories,H&M,Spring,NaN,White,62.58,8.8,57.07,2024-11-06,1,1.7,False,no_returned
1937,FB001938,Outerwear,H&M,Spring,XXL,White,109.53,29.3,77.44,2024-11-02,35,1.3,False,no_returned
1965,FB001966,Bottoms,Gap,Spring,XS,Gray,96.73,0.0,96.73,2024-11-09,18,4.8,False,no_returned
2070,FB002071,Dresses,Mango,Spring,XL,Pink,173.77,17.0,144.23,2024-11-20,5,1.9,False,no_returned
2099,FB002100,Bottoms,Forever21,Spring,XL,Green,102.76,0.0,102.76,2024-11-16,35,2.2,False,no_returned

In [ ]:
df['purchase_date'] = pd.to_datetime(df['purchase_date'])
nov_products = df[df['purchase_date'].dt.month == 7]
display(nov_products)

,product_id,category,brand,season,size,color,original_price,markdown_percentage,current_price,purchase_date,stock_quantity,customer_rating,is_returned,return_reason
0,FB000001,Outerwear,Zara,Spring,XL,Red,196.01,0.0,196.01,2025-07-05,37,3.0,False,no_returned
3,FB000004,Shoes,Uniqlo,Spring,XL,Black,75.36,0.0,75.36,2025-07-07,48,2.6,False,no_returned
56,FB000057,Tops,H&M,Spring,S,Beige,73.71,0.0,73.71,2025-07-10,35,3.9,True,Quality Issue
80,FB000081,Tops,Banana Republic,Spring,S,Navy,78.16,19.1,63.23,2025-07-25,23,NaN,False,no_returned
110,FB000111,Outerwear,Uniqlo,Spring,L,Black,92.83,0.0,92.83,2025-07-20,9,1.2,False,no_returned
119,FB000120,Outerwear,Zara,Spring,L,Red,248.58,0.0,248.58,2025-07-04,27,1.5,False,no_returned
143,FB000144,Tops,H&M,Spring,L,Beige,102.99,0.0,102.99,2025-07-16,41,3.9,False,no_returned
147,FB000148,Bottoms,Banana Republic,Spring,XXL,Brown,67.69,57.3,28.90,2025-07-24,50,4.6,False,no_returned
211,FB000212,Tops,Zara,Spring,M,Black,82.94,0.0,82.94,2025-07-17,46,1.5,False,no_returned
229,FB000230,Accessories,Ann Taylor,Spring,NaN,Beige,42.23,0.0,42.23,2025-07-14,15,NaN,False,no_returned
361,FB000362,Bottoms,Gap,Spring,XXL,Beige,97.29,0.0,97.29,2025-07-29,42,4.5,False,no_returned
427,FB000428,Bottoms,Zara,Spring,XXL,Purple,56.05,0.0,56.05,2025-07-16,9,NaN,False,no_returned
453,FB000454,Accessories,Ann Taylor,Spring,NaN,White,16.81,0.0,16.81,2025-07-31,16,2.8,False,no_returned
463,FB000464,Bottoms,H&M,Spring,XL,Red,36.85,0.0,36.85,2025-07-03,0,4.4,False,no_returned
481,FB000482,Dresses,H&M,Spring,S,Navy,123.93,30.0,86.75,2025-07-31,39,1.9,False,no_returned
523,FB000524,Accessories,Forever21,Spring,NaN,Navy,25.34,0.0,25.34,2025-07-31,17,3.3,False,no_returned
529,FB000530,Accessories,Uniqlo,Spring,NaN,Gray,15.14,36.7,9.58,2025-07-23,41,3.8,False,no_returned
534,FB000535,Shoes,Ann Taylor,Spring,XL,Red,112.60,22.0,87.83,2025-07-22,29,2.1,True,Color Mismatch
552,FB000553,Dresses,Zara,Spring,L,Beige,168.92,0.0,168.92,2025-07-14,11,4.4,False,no_returned
608,FB000609,Accessories,Forever21,Spring,NaN,Red,32.62,29.1,23.13,2025-07-27,9,1.4,False,no_returned
628,FB000629,Bottoms,Uniqlo,Spring,XL,Gray,109.81,0.0,109.81,2025-07-24,17,1.9,False,no_returned
649,FB000650,Tops,Zara,Spring,S,Purple,58.16,0.0,58.16,2025-07-02,29,4.1,False,no_returned
690,FB000691,Tops,H&M,Spring,XL,Black,61.67,46.4,33.06,2025-07-15,50,2.7,False,no_returned
695,FB000696,Shoes,Uniqlo,Spring,M,Purple,169.89,0.0,169.89,2025-07-14,12,1.2,False,no_returned
735,FB000736,Accessories,Gap,Spring,NaN,Red,79.94,0.0,79.94,2025-07-31,26,3.8,False,no_returned
782,FB000783,Bottoms,Mango,Spring,NaN,Gray,77.74,38.8,47.58,2025-07-11,23,4.3,False,no_returned
897,FB000898,Bottoms,Uniqlo,Spring,M,Pink,61.78,0.0,61.78,2025-07-30,24,3.5,False,no_returned
905,FB000906,Bottoms,Mango,Spring,XL,Pink,107.22,37.8,66.69,2025-07-11,21,2.9,False,no_returned
907,FB000908,Dresses,Forever21,Spring,S,Blue,90.52,53.2,42.36,2025-07-28,37,2.2,False,no_returned
1023,FB001024,Tops,Banana Republic,Spring,S,Brown,32.89,0.0,32.89,2025-07-08,6,4.6,False,no_returned
1050,FB001051,Dresses,Forever21,Spring,S,Blue,171.10,0.0,171.10,2025-07-23,34,NaN,False,no_returned
1141,FB001142,Accessories,Banana Republic,Spring,NaN,Gray,77.78,0.0,77.78,2025-07-07,23,2.5,True,Size Issue
1159,FB001160,Tops,Uniqlo,Spring,S,Purple,62.21,0.0,62.21,2025-07-23,38,2.6,False,no_returned
1186,FB001187,Outerwear,Ann Taylor,Spring,L,White,128.92,0.0,128.92,2025-07-10,40,1.5,False,no_returned
1191,FB001192,Shoes,H&M,Spring,XS,Green,101.00,58.6,41.81,2025-07-04,44,1.2,False,no_returned
1315,FB001316,Shoes,Banana Republic,Spring,M,Green,84.57,5.4,80.00,2025-07-17,33,NaN,False,no_returned
1353,FB001354,Accessories,Zara,Spring,NaN,Gray,77.68,29.9,54.45,2025-07-24,33,4.0,True,Damaged
1357,FB001358,Outerwear,Banana Republic,Spring,XL,Red,135.02,0.0,135.02,2025-07-30,25,3.4,True,Changed Mind
1362,FB001363,Tops,Banana Republic,Spring,S,Gray,77.30,35.1,50.17,2025-07-26,16,NaN,False,no_returned
1445,FB001446,Outerwear,Zara,Spring,S,Brown,190.03,14.9,161.72,2025-07-24,35,4.1,False,no_returned
1493,FB001494,Bottoms,Mango,Spring,S,White,111.91,0.0,111.91,2025-07-22,28,1.8,False,no_returned
1520,FB001521,Accessories,Ann Taylor,Spring,NaN,Black,52.97,0.0,52.97,2025-07-26,36,4.6,False,no_returned
1564,FB001565,Bottoms,Mango,Spring,XXL,Gray,84.80,0.0,84.80,2025-07-08,46,4.6,False,no_returned
1566,FB001567,Outerwear,Banana Republic,Spring,XS,Navy,229.17,0.0,229.17,2025-07-17,37,2.0,False,no_returned
1667,FB001668,Shoes,H&M,Spring,XXL,Purple,179.31,24.1,136.10,2025-07-13,0,3.1,False,no_returned
1691,FB001692,Accessories,Uniqlo,Spring,NaN,Purple,32.20,19.2,26.02,2025-07-27,8,4.3,False,no_returned
1711,FB001712,Tops,Gap,Spring,S,Pink,43.45,0.0,43.45,2025-07-17,30,2.3,False,no_returned
1879,FB001880,Outerwear,Uniqlo,Spring,S,Brown,138.98,10.2,124.80,2025-07-22,36,1.4,False,no_returned
1881,FB001882,Outerwear,H&M,Spring,NaN,White,151.62,0.0,151.62,2025-07-11,41,3.5,False,no_returned
1899,FB001900,Shoes,Banana Republic,Spring,XXL,Red,84.65,0.0,84.65,2025-07-26,49,3.6,False,no_returned
1994,FB001995,Shoes,Uniqlo,Spring,M,Gray,76.30,0.0,76.30,2025-07-03,35,2.6,False,no_returned
2014,FB002015,Dresses,Zara,Spring,XS,Blue,146.07,0.0,146.07,2025-07-09,33,3.7,False,no_returned
2084,FB002085,Outerwear,Gap,Spring,XS,Red,119.36,0.0,119.36,2025-07-02,30,2.7,True,Size Issue
2096,FB002097,Shoes,Uniqlo,Spring,L,Purple,103.90,0.0,103.90,2025-07-23,27,2.1,False,no_returned